"use client";

import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MantineProvider } from "@mantine/core";
import ReactQueryProviders from "@/components/utils/reactQueryProvider";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ReactQueryProviders>
      <MantineProvider withGlobalStyles withNormalizeCSS>
        <body className={inter.className}>{children}</body>
      </MantineProvider>
      </ReactQueryProviders>
    </html>
  );
}

